"""Export bundles for follow-up work, e.g. with agent-evolve (DESIGN.md §9).

The files are the entire contract: brainswarm never imports or calls
agent-evolve. If the ``agent-evolve`` CLI happens to be on PATH, its
``validate`` command is run on the draft manifest as a courtesy.
"""

from __future__ import annotations

import shutil
import subprocess
from pathlib import Path

import yaml

from agent_brainswarm import records
from agent_brainswarm.models import IdeaCard
from agent_brainswarm.state import Run


def _slug(text: str) -> str:
    return "".join(ch if ch.isalnum() else "-" for ch in text.lower()).strip("-")[:40] or "idea"


def _variants(run: Run, idea: str) -> list[IdeaCard]:
    cards = records.cards(run)
    cluster_of = run.read("data", "clusters.json")["cluster_of"]
    root = records.root_id(cards, idea)
    cluster = cluster_of.get(root)
    return [
        c
        for c in cards.values()
        if c.version == 1 and c.id != root and cluster and cluster_of.get(c.id) == cluster
    ]


def bundle(run: Run, idea: str, out_dir: Path) -> Path:
    """Write one idea's bundle; return its folder."""
    cards = records.cards(run)
    card = records.latest(cards, idea)
    folder = out_dir / f"{card.id}-{_slug(card.title)}"
    folder.mkdir(parents=True, exist_ok=True)
    chain = []
    x: str | None = card.id
    while x:
        chain.append(x)
        x = cards[x].parent_id
    open_crits = [
        c.critique
        for c in records.all_critiques(run)
        if c.counts and c.critique.idea_id in chain and c.critique.resolution == "open"
    ]
    responses = run.read("data", "responses.json") if run.exists("data", "responses.json") else {}
    open_crits = [
        c
        for c in open_crits
        if responses.get(c.id, {}).get("resolution", "open") in ("open", "conceded")
    ]

    (folder / "idea.md").write_text(
        f"# {card.title}\n\n{card.pitch}\n\n## Mechanism\n\n{card.mechanism}\n\n"
        f"## Why it might work\n\n{card.rationale}\n\n## Assumptions\n\n"
        + "\n".join(f"- {a}" for a in card.assumptions)
        + "\n\n## How it fails\n\n"
        + "\n".join(f"- {f}" for f in card.failure_modes)
        + f"\n\n## Cheapest test\n\n{card.cheapest_test}\n"
        + (f"\n## Operational spec\n\n{card.spec}\n" if card.spec else "")
    )
    variants = _variants(run, idea)
    (folder / "hypotheses.md").write_text(
        f"# Hypotheses for {card.title}\n\n"
        "Directions to try, e.g. as agent-evolve mutate/crossover material.\n\n## Variants from the same cluster\n\n"
        + ("\n".join(f"- **{v.title}**: {v.pitch}" for v in variants) or "- none")
        + "\n\n## Open critiques turned into tests\n\n"
        + (
            "\n".join(f"- Test: {c.falsifier} (addresses: {c.mechanism})" for c in open_crits)
            or "- none"
        )
        + "\n"
    )
    (folder / "implementation_brief.md").write_text(
        f"# Implementation brief: {card.title}\n\n"
        "agent-evolve improves code that already runs and has a measured baseline. Implement a first, "
        "simple, working version of this idea before evolving it.\n\n"
        f"- Start from the operational spec or mechanism above.\n- First experiment: {card.cheapest_test}\n"
        "- Write an eval command that prints the metrics below as JSON.\n"
    )
    rubric = run.read("rubric.json")
    measured = [c for c in rubric["criteria"] if c["kind"] == "measured"]
    metrics = [
        {"name": c["name"], "optimise": "maximize", "primary": i == 0}
        for i, c in enumerate(measured)
    ] or [{"name": "TODO_primary_metric", "optimise": "maximize", "primary": True}]
    manifest = {
        "version": 1,
        "problem": {
            "description": f"{card.title}: {card.pitch}",
            "mode": "algorithm",
            "eval_command": "TODO: command that prints the metrics as JSON",
            "metrics": metrics,
        },
        "scope": {"target_files": ["TODO/path/to/implementation.py"], "do_not_touch": ["tests/"]},
        "evolution": {"rounds": 4, "candidates_per_round": 3},
        "backend": {"type": "local"},
    }
    (folder / "agent-evolve.yaml").write_text(
        "# Draft generated by brainswarm; fill in the TODO fields before running /evolve.\n"
        + yaml.safe_dump(manifest, sort_keys=False)
    )
    if shutil.which("agent-evolve"):
        result = subprocess.run(
            ["agent-evolve", "validate", str(folder / "agent-evolve.yaml")],
            capture_output=True,
            text=True,
            check=False,
        )
        (folder / "validate.txt").write_text(result.stdout + result.stderr)
    return folder


def top_families(run: Run) -> list[str]:
    """Family leads in report order (from the finals fit)."""
    final = run.read("data", "final.json")
    return sorted(final["ids"], key=lambda x: final["rank"][x])
