"""Who reviews what: critic batches and the finals match schedule.

Both designs are generated by code from the run seed, before any agent
sees the ideas, so they are pre-registered (DESIGN.md §4, directive 6).

*Critic batches* are an incomplete block design: every idea appears in
``r`` batches of at most ``b`` ideas, batches are drawn at random so they
mix clusters, and the co-review graph is required to be connected (else
the preliminary fit could not compare ideas across components).

*Finals* use an incomplete round robin: each finalist meets at least ``m``
opponents; every unordered pair is judged in both presentation orders, and
the two orders always land in different dispatches, so no single context
sees a pair twice (a judge that remembers its first verdict would make the
order swap meaningless).
"""

from __future__ import annotations

import itertools
import math
from collections.abc import Mapping, Sequence
from dataclasses import dataclass

import numpy as np


@dataclass(frozen=True)
class CriticBatch:
    """One critic dispatch."""

    dispatch_id: str
    ideas: tuple[str, ...]
    model: str


@dataclass(frozen=True)
class JudgeBatch:
    """One judge dispatch: ordered (first, second) pairs."""

    dispatch_id: str
    pairs: tuple[tuple[str, str], ...]
    model: str


def _connected(groups: Sequence[Sequence[str]], ids: Sequence[str]) -> bool:
    parent = {x: x for x in ids}

    def find(a: str) -> str:
        while parent[a] != a:
            parent[a] = parent[parent[a]]
            a = parent[a]
        return a

    for g in groups:
        for x in g[1:]:
            parent[find(x)] = find(g[0])
    return len({find(x) for x in ids}) <= 1


def critic_batches(
    idea_ids: Sequence[str],
    author_model: Mapping[str, str],
    reviews_per_idea: int,
    batch_size: int,
    models: Sequence[str],
    rng: np.random.Generator,
    prefix: str = "critic",
    max_attempts: int = 50,
) -> list[CriticBatch]:
    """Assign every idea to ``reviews_per_idea`` distinct batches of size <= ``batch_size``."""
    ids = list(idea_ids)
    if not ids:
        return []
    r = min(reviews_per_idea, math.ceil(len(ids) * reviews_per_idea / batch_size))
    n_batches = max(r, math.ceil(len(ids) * reviews_per_idea / batch_size))
    for _ in range(max_attempts):
        batches: list[list[str]] = [[] for _ in range(n_batches)]
        slots = [x for x in ids for _ in range(r)]
        rng.shuffle(slots)
        ok = True
        for x in slots:
            # Least-full batch that does not already hold x (ties random).
            candidates = [i for i, b in enumerate(batches) if x not in b and len(b) < batch_size]
            if not candidates:
                ok = False
                break
            fill = min(len(batches[i]) for i in candidates)
            least = [i for i in candidates if len(batches[i]) == fill]
            batches[least[int(rng.integers(len(least)))]].append(x)
        if ok and _connected(batches, ids):
            break
    else:
        raise RuntimeError("could not build a connected critic design; enlarge batches")
    out: list[CriticBatch] = []
    for i, batch in enumerate(batches):
        order = list(batch)
        rng.shuffle(order)  # presentation order is random and recorded
        # Prefer the model that wrote the fewest ideas in this batch.
        clash = {m: sum(author_model.get(x) == m for x in order) for m in models}
        rotated = [models[(i + j) % len(models)] for j in range(len(models))]
        model = min(rotated, key=lambda m: clash[m])
        out.append(CriticBatch(f"{prefix}-{i + 1:03d}", tuple(order), model))
    return out


def match_pairs(
    ids: Sequence[str], matches_per_idea: int, rng: np.random.Generator
) -> list[tuple[str, str]]:
    """Unordered pairs so that every idea meets >= ``matches_per_idea`` opponents.

    Greedy on the least-played idea, pairing it with a random least-played
    opponent it has not met. If ``matches_per_idea >= len(ids) - 1`` this is
    the full round robin.
    """
    ids = list(ids)
    n = len(ids)
    if n < 2:
        return []
    if matches_per_idea >= n - 1:
        return list(itertools.combinations(ids, 2))
    played = {x: 0 for x in ids}
    met: set[frozenset[str]] = set()
    pairs: list[tuple[str, str]] = []
    while min(played.values()) < matches_per_idea:
        low = min(played.values())
        lows = [x for x in ids if played[x] == low]
        a = lows[int(rng.integers(len(lows)))]
        options = [y for y in ids if y != a and frozenset((a, y)) not in met]
        if not options:
            break
        fewest = min(played[y] for y in options)
        best = [y for y in options if played[y] == fewest]
        b = best[int(rng.integers(len(best)))]
        met.add(frozenset((a, b)))
        pairs.append((a, b))
        played[a] += 1
        played[b] += 1
    return pairs


def judge_batches(
    pairs: Sequence[tuple[str, str]],
    per_dispatch: int,
    models: Sequence[str],
    rng: np.random.Generator,
    prefix: str = "judge",
) -> list[JudgeBatch]:
    """Split both orders of every pair into dispatches; the two orders never share one."""
    forward = [(a, b) for a, b in pairs]
    backward = [(b, a) for a, b in pairs]
    rng.shuffle(forward)
    rng.shuffle(backward)
    out: list[JudgeBatch] = []
    for half, offset in ((forward, 0), (backward, 1)):
        for j, start in enumerate(range(0, len(half), per_dispatch)):
            chunk = tuple(half[start : start + per_dispatch])
            # The reverse half is shifted by one model so a pair's two orders
            # are judged by different models whenever more than one is set.
            model = models[(j + offset) % len(models)]
            out.append(JudgeBatch(f"{prefix}-{len(out) + 1:03d}", chunk, model))
    return out


# Boundary rule, fixed in advance: ideas whose probability of being in the
# top k lies in [0.2, 0.8] are genuinely uncertain members of the shortlist.
BOUNDARY_LOW = 0.2
BOUNDARY_HIGH = 0.8


def boundary_pairs(
    p_top_k: Mapping[str, float],
    already: Sequence[tuple[str, str]],
    extra_per_idea: int,
    rng: np.random.Generator,
) -> list[tuple[str, str]]:
    """Extra unordered pairs among uncertain ideas near the top-k cutoff."""
    uncertain = [x for x, p in p_top_k.items() if BOUNDARY_LOW <= p <= BOUNDARY_HIGH]
    if len(uncertain) < 2:
        return []
    met = {frozenset(p) for p in already}
    fresh = [p for p in itertools.combinations(sorted(uncertain), 2) if frozenset(p) not in met]
    rng.shuffle(fresh)
    count = {x: 0 for x in uncertain}
    chosen: list[tuple[str, str]] = []
    for a, b in fresh:
        if count[a] < extra_per_idea and count[b] < extra_per_idea:
            chosen.append((a, b))
            count[a] += 1
            count[b] += 1
    return chosen
